Add Typescript declarations
satya164/jest-file-snapshot pull request #4
Opened 2018-10-12 22:33 UTC by colinking

This PR adds a Typescript declaration file, to resolve https://github.com/satya164/jest-file-snapshot/issues/2

2018-10-13 08:17 UTC, Esemesek requested changes
In addition to adding EOF, you should also link those types inside `package.json`.

2018-10-13 08:17 UTC, Esemesek commented on types/index.d.ts
> +}
Add EOF. C:

2018-10-16 11:51 UTC, satya164 commented
Hey @colinking ! Would be awesome if you can address @Esemesek's review :)

2018-10-16 11:51 UTC, satya164 commented on types/index.d.ts
> +   interface Expect {
nit: wrong indentation

2018-10-17 05:48 UTC, colinking commented
Updated the PR with your feedback. Thanks! 😄

2018-10-17 11:12 UTC, satya164 commented
Merged in 392dcd1368ecab296473455329feea17c6aa8492

2018-10-17 11:12 UTC, closed without merging